# Generated by Django 2.2.5 on 2019-09-13 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='qrcode',
            new_name='qrcod',
        ),
    ]
